# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('data_location', models.CharField(default='', max_length=200)),
                ('run_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
