# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='first_name',
            new_name='affiliation',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='data_location',
            new_name='fun_fact',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='run',
            name='email',
        ),
    ]
